##################################################################################
## 
## VERSION      :   0.0.2
## DATE         :   03/10/2016
##
## DESCRIPTION  :   ""
##
##################################################################################

version: '2'
services:
  probe:
    image: weaveworks/scope:0.17.1
    network_mode: "host"
    pid: "host"
    privileged: true
    labels:
      - "works.weave.role=system"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
    command:
      - "--probe.docker"
      - "true"
  dbdata:
    image: mongo
    volumes:
      - "/data/db:/data/db"
    command: --break-mongo
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes_from:
      - dbdata
    command: --smallfiles --rest
  websocket-server:
    build: ./websocket-server/
    container_name: websocketServer
    volumes:
      - ./websocket-server/src:/src
      - ./websocket-server/package.json:/package.json
    ports:
      - "8085:8085"
    environment:
      - PORT=8085
      - DB=bestSpot4Me
      - DB_HOST=db
      - DB_PORT=27017
      - DB_URL=mongodb://db:27017/bestSpot4Me
      - DB_USERNAME=admin
      - DB_PASSWORD=admin
      - JWT_TOKEN=ILoveReactJS
    links:
      - db
  rest-api:
    build: ./api-server/
    container_name: apiServer
    volumes:
      - ./api-server/src:/src
      - ./api-server/package.json:/package.json
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
      - DB=bestSpot4Me
      - DB_HOST=db
      - DB_PORT=27017
      - DB_URL=mongodb://db:27017/bestSpot4Me
      - DB_USERNAME=admin
      - DB_PASSWORD=admin
      - JWT_TOKEN=ILoveReactJS
      - POSTMARK_TOKEN=4b466ec2-cf66-4b02-8b0d-2e96e4433708
      - POSTMARK_FROM=no-reply@bestspot4me.com
    links:
      - db
  webapp:
    build: ./client/web/
    container_name: webapp
    volumes:
      - ./client/web/app:/app
      - ./client/web/package.json:/package.json
      - ./client/common:/common
    ports:
      - "80:80"
    links:
      - rest-api
    environment:
      - PORT=80

  nginx:
    image: nginx:1.10.1
    depends_on:
      - webapp
      - rest-api
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/nginx.conf.template
    ports:
      - "7979:80"
    environment:
      - NGINX_HOST=nginx
      - NGINX_PORT=80
    command: /bin/bash -c "envsubst < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"