##################################################################################
## 
## VERSION      :   0.0.2
## DATE         :   03/10/2016
##
## DESCRIPTION  :   ""
##
##################################################################################

version: '2'
services:
  dbdata:
    image: tianon/true
    volumes:
      - "/data/db"
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes_from:
      - dbdata
    command: "--smallfiles --logpath=/dev/null"
  rest-api:
    build: ./server/
    container_name: apiServer
    volumes:
      - ./server/src:/src
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - DB=bestSpot4Me
      - DB_HOST=db
      - DB_PORT=27017
      - DB_URL=mongodb://db:27017/bestSpot4Me
      - DB_USERNAME=admin
      - DB_PASSWORD=admin
      - JWT_TOKEN=ILoveReactJS
      - POSTMARK_TOKEN=4b466ec2-cf66-4b02-8b0d-2e96e4433708
      - POSTMARK_FROM=no-reply@bestspot4me.com
    links:
      - db
  webapp:
    build: ./app/web/
    container_name: webapp
    volumes:
      - ./client/web/app:/app
      - ./client/common:/common
    ports:
      - "80:80"
    links:
      - db
    environment:
      - PORT=80